### PR TITLE
Edit

### PR DESCRIPTION
**Pull request by kara**

### CODE REVIEW

**Comment by jkresner** [comment]
@kara please don't merge the edit branch into master thanks :)

**Comment by jkresner** [comment]
In the process of fixing some UX and explaining this better thanks!!

**Comment by kara** [comment]
Sorry :)

**Comment by jkresner** [comment]
Nah it's my bad. About 50% of authors have done this hah.
ᐧ

On Wed, Mar 18, 2015 at 4:46 PM, Kara notifications@github.com wrote:

> Sorry :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airpair/creating-container-components-part-2-angular-1-directives/pull/2#issuecomment-83226337
> .

## 

Jonathon Kresner
about.me http://about.me/jonathonkresner | hackerpreneurialism
http://hackerpreneurialism.com | @hackerpreneur
http://twitter.com/hackerpreneur

**Pull request merged**
